version: 2

jobs:
  test:
    docker: [{image: "rust:1.63.0"}]
    environment:
      CARGO_LOG: cargo::core::compiler::fingerprint=trace
    steps:
      - checkout
      - restore_cache: { key: 'cargo-registry' }
      - restore_cache: { key: 'cargo-crates-{{ checksum "Cargo.lock" }}' }
      - restore_cache: { key: 'target-{{ checksum "Cargo.lock" }}' }
      - run: cargo build --locked
      - save_cache:
          key: 'cargo-registry'
          paths: [ /usr/local/cargo/registry/index ]
      - save_cache:
          key: 'cargo-crates-{{ checksum "Cargo.lock" }}'
          paths: [ /usr/local/cargo/registry/cache, /usr/local/cargo/registry/git ]
      - save_cache:
          key: 'target-{{ checksum "Cargo.lock" }}'
          paths: [ target ]

workflows:
  version: 2
  build:
    jobs:
      - test
